# Generated by Django 3.2.15 on 2022-10-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('site_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Auteur',
                'ordering': ('firstname', 'lastname'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('google_link', models.URLField(blank=True)),
                ('page_count', models.SmallIntegerField(blank=True, null=True)),
                ('image_link', models.URLField(blank=True)),
                ('isbn_13', models.CharField(blank=True, max_length=13, null=True)),
                ('buy_link', models.URLField(blank=True)),
                ('author', models.ManyToManyField(related_name='mes_autheurs', to='apibook.Author')),
                ('categorie', models.ManyToManyField(to='apibook.Category')),
            ],
        ),
    ]
