# Generated by Django 3.2.15 on 2022-10-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibook', '0002_auto_20221025_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
