# Generated by Django 3.2.15 on 2023-02-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibook', '0003_rename_author_book_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamTimerPrayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('methode', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=5)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
